/****************************************************************************
 *
 * genspheres -- Generate input for omp-c-ray
 *
 * Copyright (C) 2022 Moreno Marzolla <moreno.marzolla(at)unibo.it>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 ****************************************************************************/

/***
% HPC -- Generate input for omp-c-ray
% Moreno Marzolla <moreno.marzolla@unibo.it>
% Last modified 2022-03-20

Inspired by <https://twitter.com/pickover/status/1505350972641525765>

Compile with:

        gcc -std=c99 -Wall -Wpedantic genspheres.c -o genspheres

Run with:

        ./genspheres | ./omp-c-ray -o spheres.pbm

***/

#include <stdio.h>
#include <stdlib.h>

/**
 * A sphere of radius sz and center (cx, cy, cz)
 */
void sphere( float sz, float cx, float cy, float cz )
{
    printf("s  %f %f %f  %f  0.0 0.0 0.2  40 0.9\n",
           cx, cy, cz, sz);
}

int main( int argc, char *argv[] )
{
    int size = 10;

    if (argc > 2) {
        fprintf(stderr, "Usage %s [size]\n", argv[0]);
        return EXIT_FAILURE;
    }

    if (argc > 1) {
        size = atoi(argv[1]);
    }

    printf("# Input for omp-c-ray\n");
    printf("# Generated by %s %d\n", argv[0], size);
    for (int i=0; i<size; i++) {
        for (int j=0; j<size; j++) {
            sphere(0.5, i, 0.8, j);
            sphere(0.5, i, -0.8, j);
        }
    }
    printf("s  0   -10050 0    10000    0.2 0.35 0.5    80.0    0.4\n"); /* floor   */
    printf("l -50 100 -50\n"); /* lights */
    printf("l 10 0 0\n");
    printf("c  -1.5 0 -1.5   170  0 0 0\n"); /* camera */

    return EXIT_SUCCESS;
}
